import { KnowledgeBase } from './types';

export const FANY_KNOWLEDGE_BASE: KnowledgeBase = {
  "descripcion_general": "Base de conocimiento técnica para Fany IA Asistent. Incluye información estructurada en cinco áreas: Programación Web, Soporte Técnico de PCs, Aprendizaje de Inteligencia Artificial, Marketing Digital y Educación.",
  "conocimientos": [
    { "titulo": "Estructura del DOM en HTML", "contenido": "El Document Object Model (DOM) representa la estructura jerárquica de un documento HTML. Permite manipular elementos mediante lenguajes de scripting como JavaScript.", "categoria": "Programación Web", "etiquetas": "html,dom,frontend,documento" },
    { "titulo": "Principios de CSS Modular", "contenido": "CSS modular promueve la reutilización de estilos mediante clases independientes. Facilita el mantenimiento del código y evita conflictos de nombres.", "categoria": "Programación Web", "etiquetas": "css,modularidad,frontend,estilos" },
    { "titulo": "Buenas prácticas con JavaScript ES6+", "contenido": "Utilizar const y let en lugar de var, emplear funciones flecha, desestructuración y plantillas literales mejora la legibilidad y seguridad del código.", "categoria": "Programación Web", "etiquetas": "javascript,es6,frontend,buenas practicas" },
    { "titulo": "Gestión de dependencias con NPM", "contenido": "NPM permite instalar, actualizar y administrar paquetes en proyectos JavaScript. El archivo package.json define las dependencias y scripts del proyecto.", "categoria": "Programación Web", "etiquetas": "npm,dependencias,nodejs,gestion" },
    { "titulo": "Uso de React para desarrollo SPA", "contenido": "React permite construir aplicaciones de una sola página (SPA) mediante componentes reutilizables y un DOM virtual que optimiza el rendimiento.", "categoria": "Programación Web", "etiquetas": "react,spa,frontend,componentes" },
    { "titulo": "Principios de RESTful APIs", "contenido": "Las APIs RESTful utilizan los métodos HTTP (GET, POST, PUT, DELETE) para interactuar con recursos. Se caracterizan por ser sin estado y escalables.", "categoria": "Programación Web", "etiquetas": "api,rest,backend,desarrollo web" },
    { "titulo": "Autenticación JWT en Node.js", "contenido": "Los JSON Web Tokens permiten autenticar usuarios mediante tokens firmados. En Node.js se implementan comúnmente con la librería jsonwebtoken.", "categoria": "Programación Web", "etiquetas": "jwt,autenticacion,nodejs,seguridad" },
    { "titulo": "Conceptos de seguridad en aplicaciones web", "contenido": "Incluyen protección contra XSS, CSRF y ataques de inyección. Las cabeceras HTTP seguras y la validación del lado servidor son esenciales.", "categoria": "Programación Web", "etiquetas": "seguridad,web,xss,csrf,inyeccion" },
    { "titulo": "Optimización de rendimiento en Frontend", "contenido": "Minificación de recursos, uso de CDN, carga diferida y compresión de imágenes son técnicas clave para mejorar el rendimiento del frontend.", "categoria": "Programación Web", "etiquetas": "rendimiento,frontend,optimizacion,cdn" },
    { "titulo": "Configuración de entornos con Webpack", "contenido": "Webpack es un empaquetador de módulos que permite combinar, minificar y optimizar recursos de un proyecto web moderno.", "categoria": "Programación Web", "etiquetas": "webpack,frontend,build,automatizacion" },
    { "titulo": "Diseño responsivo con Flexbox y Grid", "contenido": "Flexbox y CSS Grid permiten crear diseños adaptables. Flexbox gestiona alineaciones unidimensionales y Grid estructuras bidimensionales.", "categoria": "Programación Web", "etiquetas": "css,responsive,grid,flexbox" },
    { "titulo": "Consumo de APIs con Fetch y Axios", "contenido": "Fetch y Axios son herramientas para realizar solicitudes HTTP. Axios ofrece una sintaxis simplificada y manejo avanzado de errores.", "categoria": "Programación Web", "etiquetas": "api,fetch,axios,http" },
    { "titulo": "Gestión de estado con Redux", "contenido": "Redux centraliza el estado de la aplicación y facilita su gestión predecible mediante un flujo unidireccional de datos.", "categoria": "Programación Web", "etiquetas": "redux,estado,react,frontend" },
    { "titulo": "Uso de TypeScript en proyectos web", "contenido": "TypeScript extiende JavaScript con tipado estático y herramientas que mejoran la escalabilidad y mantenibilidad del código.", "categoria": "Programación Web", "etiquetas": "typescript,tipado,desarrollo web" },
    { "titulo": "Integración continua con GitHub Actions", "contenido": "GitHub Actions permite automatizar pruebas, despliegues y compilaciones mediante flujos de trabajo definidos en YAML.", "categoria": "Programación Web", "etiquetas": "github,ci,automatizacion,devops" },
    { "titulo": "Mantenimiento preventivo de hardware", "contenido": "Incluye limpieza física, revisión de ventiladores, comprobación de temperatura y actualización de firmware para evitar fallos futuros.", "categoria": "Soporte Técnico de PCs", "etiquetas": "hardware,mantenimiento,prevencion" },
    { "titulo": "Análisis de fallos en memoria RAM", "contenido": "El uso de herramientas como MemTest86 permite detectar errores en módulos RAM. Los fallos pueden provocar reinicios o pantallazos azules.", "categoria": "Soporte Técnico de PCs", "etiquetas": "ram,diagnostico,hardware,errores" },
    { "titulo": "Gestión de controladores en Windows", "contenido": "Los controladores garantizan la comunicación entre hardware y sistema operativo. Deben mantenerse actualizados desde fuentes oficiales.", "categoria": "Soporte Técnico de PCs", "etiquetas": "drivers,windows,actualizacion" },
    { "titulo": "Diagnóstico de discos duros con SMART", "contenido": "El sistema SMART supervisa parámetros de salud del disco. Valores anómalos indican posibles fallos inminentes de hardware.", "categoria": "Soporte Técnico de PCs", "etiquetas": "disco duro,smart,hardware,diagnostico" },
    { "titulo": "Resolución de conflictos de software", "contenido": "Conflictos entre aplicaciones pueden deberse a incompatibilidades o dependencias rotas. Se recomienda reinstalar o ejecutar en modo seguro.", "categoria": "Soporte Técnico de PCs", "etiquetas": "software,errores,soporte,windows" },
    { "titulo": "Optimización del arranque del sistema", "contenido": "Reducir procesos de inicio mejora la velocidad de carga. Herramientas como msconfig o el Administrador de tareas ayudan a gestionarlos.", "categoria": "Soporte Técnico de PCs", "etiquetas": "rendimiento,arranque,windows,optimizar" },
    { "titulo": "Solución de errores de red TCP/IP", "contenido": "Comandos como netsh int ip reset y ipconfig /flushdns restablecen configuraciones de red. Es útil ante pérdida de conectividad.", "categoria": "Soporte Técnico de PCs", "etiquetas": "red,tcpip,conexion,soporte" },
    { "titulo": "Reinstalación limpia de Windows", "contenido": "Un formateo e instalación limpia elimina errores persistentes. Debe respaldarse la información antes del proceso.", "categoria": "Soporte Técnico de PCs", "etiquetas": "windows,instalacion,sistema operativo" },
    { "titulo": "Gestión de seguridad y antivirus", "contenido": "Los antivirus deben mantenerse actualizados. Complementar con firewall y análisis periódicos garantiza una mayor protección.", "categoria": "Soporte Técnico de PCs", "etiquetas": "seguridad,antivirus,proteccion" },
    { "titulo": "Restauración del sistema en Windows", "contenido": "Permite revertir el sistema a un estado anterior sin afectar archivos personales. Útil tras instalaciones defectuosas o errores críticos.", "categoria": "Soporte Técnico de PCs", "etiquetas": "restauracion,windows,sistema" }
  ]
};